/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "MainComponent.h"
#include "FilesPane.h"
#include "MidiPane.h"
#include <windows.h>
#include <stdio.h>
#include <shellapi.h>

//==============================================================================
class seq64Application  : public JUCEApplication
{
public:
    //==============================================================================
    seq64Application() {}

    const String getApplicationName() override       { return ProjectInfo::projectName; }
    const String getApplicationVersion() override    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed() override       { return true; }

    //==============================================================================
    void initialise (const String& commandLine) override
    {
        // This method is where you should put your application's initialisation code..

		String romName;
		String descriptorName;
		String midiNumberStr;
		String output;

		LPWSTR *szArglist;
		int nArgs;

		szArglist = CommandLineToArgvW(GetCommandLineW(), &nArgs);

		for (int x = 0; x < nArgs; x++)
		{
			String commandLineStr = String(szArglist[x]);
			commandLineStr = commandLineStr.trim();
			
			if (commandLineStr.startsWith("-rom="))
			{
				romName = commandLineStr.substring(commandLineStr.indexOf("-rom=")+5);
				romName = romName.trim();
			}

			else if (commandLineStr.contains("-descriptor="))
			{
				descriptorName = commandLineStr.substring(commandLineStr.indexOf("-descriptor=")+12);
				descriptorName = descriptorName.trim();
			}
			else if (commandLineStr.contains("-midi="))
			{
				midiNumberStr = commandLineStr.substring(commandLineStr.indexOf("-midi=")+6);
				midiNumberStr = midiNumberStr.trim();
			}
			else if (commandLineStr.contains("-output="))
			{
				output = commandLineStr.substring(commandLineStr.indexOf("-output=")+8);
				output = output.trim();
			}
		}

		int midiNumber = midiNumberStr.getIntValue();

        mainWindow = new MainWindow();

		mainWindow->mainComponent->romfile = File(romName);
		mainWindow->mainComponent->romdescfile = File(descriptorName);

		mainWindow->setName("seq64");

		mainWindow->mainComponent->menuItemSelected(1, 0);
		mainWindow->mainComponent->menuItemSelected(11, 0);

		for (int x = 0; x < mainWindow->mainComponent->filespane->kfilelistnode.getNumChildren(); x++)
		{
			ValueTree selkfile = mainWindow->mainComponent->filespane->kfilelistnode.getChild(x);
			String type = selkfile.getProperty("type", "Unsupported");
			if (type == "Audioseq Index")
			{
				mainWindow->mainComponent->filespane->lstKFiles->selectRow(x);
				mainWindow->mainComponent->filespane->rowSelected(mainWindow->mainComponent->filespane->lsmKFiles, x);
				break;
			}
		}

		//mainWindow->mainComponent->filespane->lstIndex->selectRow(0);
		
		mainWindow->mainComponent->filespane->rowSelected(mainWindow->mainComponent->filespane->lsmIndex, midiNumber);
		
		mainWindow->mainComponent->filespane->buttonClicked(mainWindow->mainComponent->filespane->btnLoadEntry);

		mainWindow->mainComponent->midipane->dest = output;
		mainWindow->mainComponent->midipane->buttonClicked(mainWindow->mainComponent->midipane->btnMIDIExport);

		JUCEApplication::getInstance()->systemRequestedQuit();
    }

    void shutdown() override
    {
        // Add your application's shutdown code here..

        mainWindow = nullptr; // (deletes our window)
    }

    //==============================================================================
    void systemRequestedQuit() override
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine) override
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }

    //==============================================================================
    /*
        This class implements the desktop window that contains an instance of
        our MainContentComponent class.
    */
    class MainWindow    : public DocumentWindow
    {
    public:
		MainComponent* mainComponent;

        MainWindow()  : DocumentWindow ("MainWindow",
                                        Colours::lightgrey,
                                        DocumentWindow::allButtons)
        {
			mainComponent = new MainComponent(*this);
            setContentOwned (mainComponent, true);

            centreWithSize (getWidth(), getHeight());
            setVisible (false);
        }

        void closeButtonPressed()
        {
            // This is called when the user tries to close this window. Here, we'll just
            // ask the app to quit when this happens, but you can change this to do
            // whatever you need.
            JUCEApplication::getInstance()->systemRequestedQuit();
        }

        /* Note: Be careful if you override any DocumentWindow methods - the base
           class uses a lot of them, so by overriding you might break its functionality.
           It's best to do all your work in your content component instead, but if
           you really have to override any DocumentWindow methods, make sure your
           subclass also calls the superclass's method.
        */

    private:
        JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MainWindow)
    };

private:
    ScopedPointer<MainWindow> mainWindow;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (seq64Application)
